In [23]:
import polars as pl
import polars.selectors as cs

df = pl.read_csv(
    "../data/raw/source=gps/date=2026-05-23/gps_20260523_040000.csv"
    , has_header=False
    , new_columns=
    [
        "transport_type"        # 1=trolleybus, 2=bus, 3=tram, 7=night bus
        , "line_number"         # string: e.g. `"8"`, `"18A"`
        , "longitude_raw"       # Longitude × 1,000,000 (WGS84)
        , "latitude_raw"        # Latitude × 1,000,000 (WGS84)
        , "speed_kmh"           # Empty string when unavailable
        , "heading_deg"         # `999` when unavailable
        , "vehicle_id"          # Internal vehicle identifier
        , "floor_type"          # Z = low-floor, false = unknown
        , "fleet_number"        # Physical vehicle serial number
        , "destination"         # Destination stop name
    ])

In [11]:
df.head()

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ transport ┆ line_numb ┆ longitude ┆ latitude_ ┆ … ┆ vehicle_i ┆ floor_typ ┆ fleet_num ┆ destinat │
│ _type     ┆ er        ┆ _raw      ┆ raw       ┆   ┆ d         ┆ e         ┆ ber       ┆ ion      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ str       ┆ i64       ┆ i64       ┆   ┆ i64       ┆ str       ┆ i64       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 3         ┆ 2         ┆ 24668960  ┆ 59461280  ┆ … ┆ 98        ┆ Z         ┆ 106       ┆ Kopli    │
│ 3         ┆ 2         ┆ 24784690  ┆ 59430110  ┆ … ┆ 99        ┆ Z         ┆ 144       ┆ Kopli    │
│ 3         ┆ 1         ┆ 24706050  ┆ 59452360  ┆ … ┆ 102       ┆ Z         ┆ 166       ┆ Kopli    │
│ 3         ┆ 1         ┆ 24738840  ┆ 59441090  ┆ … ┆ 110       ┆ Z         ┆ 31        ┆ Kadriorg │
│ 3         ┆ 5         ┆ 24753360  ┆ 59437210  ┆ … ┆ 123       ┆ Z         ┆ 64        ┆ Kopli    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [21]:
df.select("speed_kmh").unique()

shape: (1, 1)
┌───────────┐
│ speed_kmh │
│ ---       │
│ str       │
╞═══════════╡
│ null      │
└───────────┘

In [ ]:
df.select([cs.all(), pl.col("transport_type").lt(3).alias("lt3")])

In [ ]:
df.with_columns(
    pl.when(pl.col.tr > 2)
    .then(1)
    .when(pl.col.bar > 2)
    .then(4)
    .otherwise(-1)
    .alias("val")
)